DROP TABLE IF EXISTS leagues;
DROP TABLE IF EXISTS nation;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS coaches;
DROP TABLE IF EXISTS stats;